name: kitpvp
version: 1.2
author: _Ug
description: kitpvp.org plugin
main: org.kitpvp.core.Core
commands:
  dev:
    description: Developer command!
  bal:
    description: Check your balance
  setrank:
    description: Set ranks!
  pay:
    description: Pay money/coins/series!
  msg:
    description: Message a player!
  message:
    description: Message a player!
  r:
    description: Reply to a message!
  stats:
    description: Check your stats.